# Generated by Django 3.1.6 on 2021-02-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='referer',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
