# Generated by Django 3.1.6 on 2021-02-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0003_auto_20190528_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.urlmap')),
            ],
        ),
    ]
