# Generated by Django 3.1.6 on 2021-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visit_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='referer',
            field=models.TextField(null=True),
        ),
    ]
