# Generated by Django 3.1.6 on 2021-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190528_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlprofile',
            name='enabled',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
