# Generated by Django 3.1.6 on 2021-02-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20210212_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmap',
            name='full_url',
            field=models.CharField(max_length=500),
        ),
    ]
